CREATE TABLE HistoricoUniversidade (
    MAT int,
    COD_DISC int,
    COD_TURMA int,
    COD_PROF int,
    ANO int,
    FREQUENCIA varchar,
    NOTA int,
    PRIMARY KEY (MAT, COD_DISC, COD_TURMA, COD_PROF, ANO),
    FOREIGN KEY (MAT) REFERENCES AlunosUniversidade (MAT)
);

SELECT AU.MAT, AVG(HU.NOTA) AS MEDIA_NOTAS_POO
FROM AlunosUniversidade AU
JOIN HistoricoUniversidade HU ON AU.MAT = HU.MAT
WHERE HU.COD_DISC = 'POO' AND HU.ANO = 2015
GROUP BY AU.MAT
HAVING AVG(HU.NOTA) > 6;

SELECT COUNT(DISTINCT AU.MAT) AS QUANTIDADE_ALUNOS_NAO_NATAL
FROM AlunosUniversidade AU
WHERE AU.CIDADE <> 'NATAL';

